export { default as Footer } from './Footer';
export { default as InfoGrid } from './InfoGrid';
// export { default as TerminalAnimation } from './TerminalAnimation';
export { default as Navbar } from './Navbar';
export { default as AnimatedTextCharacter } from './AnimatedTextCharacter';
export { default as Experience } from './Experience';
export { default as AnimatedBackground } from './AnimatedBackground';
export { default as ProjectShowcase } from './ProjectShowcase';
export { default as TechStack } from './TechStack';
export { default as AboutMe } from './AboutMe';
export { default as CallToActionSection } from './SpinningTextSection';
export { default as ContactPopup } from './ContactPopup';
export { default as ProjectCard } from './ProjectCard';
