// import {DiMysql,DiPostgresql, DiMongodb, DiJavascript,DiSqllite, DiMsqlServer} from "react-icons/di";
// import {
//     SiExpress,
//     SiNestjs,
//     SiNextdotjs,
//     SiTypescript,
//     SiTailwindcss,
//     SiSupabase,
//     SiFramer,
//     // SiGsap,
//     SiThreedotjs,
//     SiFirebase,
//     // SiMicrosoftazure,
//     SiJest,
//     SiQt,
//     SiElectron,
//     SiExpo,
//     SiReactquery,
//     SiGraphql,
//     SiCplusplus
// } from "react-icons/si";
// import {
//     FaNode,
//     FaReact,
//     FaPython,
//     FaAws,
//     FaGithub,
//     FaGit,
// } from "react-icons/fa";
// import { TbBrandReactNative } from "react-icons/tb";
// import { IoLogoHtml5, IoLogoCss3 } from "react-icons/io5";

// export const icons = [
//     // DiMysql,
//     DiPostgresql,
//     DiMongodb,
//     // DiMsqlServer,
//     SiExpress,
//     FaNode,
//     SiGraphql,
//     // SiNestjs,
//     SiNextdotjs,
//     FaReact,
//     SiTypescript,
//     // DiJavascript,
//     // SiReactquery,
//     SiExpo,
//     SiElectron,
//     // TbBrandReactNative,
//     SiCplusplus,
//     SiQt,
//     IoLogoHtml5,
//     IoLogoCss3,
//     SiTailwindcss,
//     FaGit,
//     // FaGithub,
//     // FaAws,
//     SiFirebase,
//     // SiMicrosoftazure,
//     // DiSqllite,
//     // FaPython,
//     // SiJest,
//     SiSupabase,
//     // SiFramer,
//     // SiGsap,
//     SiThreedotjs,
//   ];

  export const slugs = [
    "mysql",
    "postgresql",
    "mongodb",
    "microsoftsqlserver",
    "express",
    "nodedotjs",
    "graphql",
    "nestjs",
    "nextdotjs",
    "react",
    "typescript",
    "javascript",
    "expo",
    "electron",
    "cplusplus",
    "qt",
    "html5",
    "css3",
    "tailwindcss",
    "git",
    "github",
    "amazonaws",
    "firebase",
    "microsoftazure",
    "sqlite",
    "python",
    "jest",
    "supabase",
    "gsap",
    "threedotjs",
    "reactquery",
    "prisma", // Including Prisma as it's common with these tools
    "vercel"  // Vercel deployment
  ];